<?php
/**
 * VoltTest load test for the Symfony shop target.
 *
 * Four scenarios share one virtual-user pool:
 *   1. API browse + add to cart   (weight 50)  JWT login, product list, product, cart
 *   2. API checkout               (weight 20)  JWT login, add to cart, checkout
 *   3. HTML shopper               (weight 30)  form login with CSRF, product page,
 *                                              add-to-cart form, cart, checkout, logout
 *   4. API flash sale             (weight 15)  every VU buys the same scarce product;
 *                                              proves checkout never oversells
 *
 * Usage:
 *   TARGET_URL=http://localhost:8088 php symfony-shop-test.php            # headless, local engine
 *   TARGET_URL=https://<fly-host> VOLTTEST_API_KEY=... php symfony-shop-test.php   # cloud run
 *
 * Optional: VUS (default 200), DURATION (default 2m), RAMP_UP (default 30s),
 *           SCENARIOS (comma list of api-browse,api-checkout,html,flash-sale; default all),
 *           STAGES ("1m:50,1m:100,2m:200" = staged load instead of constant VUS/DURATION/RAMP_UP),
 *           DATA_DIR (directory holding users-*.csv; default ./data, use ./data/fly for the Fly deploy),
 *           REGIONS (cloud only, e.g. "us-east-1:100").
 */

require __DIR__.'/vendor/autoload.php';

use VoltTest\DataSourceConfiguration;
use VoltTest\VoltTest;

$base = rtrim(getenv('TARGET_URL') ?: 'http://localhost:8088', '/');
$vus = (int) (getenv('VUS') ?: 200);
$duration = getenv('DURATION') ?: '2m';
$rampUp = getenv('RAMP_UP') ?: '30s';

// email,password,product_id,quantity — generated by `bin/console app:export-users`.
// Each scenario gets its own disjoint shard so one account is never in two
// flows at the same time (an API checkout would empty the HTML shopper's cart).
// DATA_DIR selects which export to use (e.g. data/fly for the CSVs pulled from the Fly deploy).
$dataDir = rtrim(getenv('DATA_DIR') ?: __DIR__.'/data', '/');
$users = fn (int|string $shard) => new DataSourceConfiguration("$dataDir/users-$shard.csv", 'unique', true);

$enabled = array_filter(array_map('trim', explode(',', getenv('SCENARIOS') ?: 'api-browse,api-checkout,html,flash-sale')));
$wants = fn (string $key) => in_array($key, $enabled, true);

$test = new VoltTest('Symfony Shop', 'JSON API + HTML forms against a production-mode Symfony 7.4 app');
$test->target($base);

// STAGES="1m:50,1m:100,1m:200,2m:400" ramps through targets to find the
// saturation point; without it the load is constant (VUS/DURATION/RAMP_UP).
if ($stages = getenv('STAGES')) {
    foreach (explode(',', $stages) as $stage) {
        [$stageDuration, $target] = explode(':', trim($stage));
        $test->stage($stageDuration, (int) $target);
    }
} else {
    $test->setVirtualUsers($vus)->setDuration($duration)->setRampUp($rampUp);
}

// ---------------------------------------------------------------------------
// Scenario 1: API browse + add to cart
// ---------------------------------------------------------------------------
if ($wants('api-browse')) {
$browse = $test->scenario('API: browse and add to cart')
    ->setWeight(50)
    ->setThinkTime('1s')
    ->setDataSourceConfiguration($users(1));

$browse->step('Login (JWT)')
    ->post("$base/api/v1/login", '{"email":"${email}","password":"${password}"}')
    ->header('Content-Type', 'application/json')
    ->validateStatus('login ok', 200)
    ->extractFromJson('token', 'token');

$browse->step('List products')
    ->get("$base/api/v1/products?page=1&per_page=12")
    ->header('Accept', 'application/json')
    ->validateStatus('list ok', 200);

$browse->step('Product detail')
    ->get("$base/api/v1/products/\${product_id}")
    ->header('Accept', 'application/json')
    ->validateStatus('product ok', 200);

$browse->step('Add to cart')
    ->post("$base/api/v1/cart/items", '{"product_id":${product_id},"quantity":${quantity}}')
    ->header('Content-Type', 'application/json')
    ->header('Authorization', 'Bearer ${token}')
    ->validateStatus('cart item created', 201)
    ->extractFromJson('cart_id', 'data.cart_id');

$browse->step('View cart')
    ->get("$base/api/v1/cart")
    ->header('Authorization', 'Bearer ${token}')
    ->validateStatus('cart ok', 200);
}

// ---------------------------------------------------------------------------
// Scenario 2: API checkout
// ---------------------------------------------------------------------------
if ($wants('api-checkout')) {
$checkout = $test->scenario('API: checkout')
    ->setWeight(20)
    ->setThinkTime('1s')
    ->setDataSourceConfiguration($users(2));

$checkout->step('Login (JWT)')
    ->post("$base/api/v1/login", '{"email":"${email}","password":"${password}"}')
    ->header('Content-Type', 'application/json')
    ->validateStatus('login ok', 200)
    ->extractFromJson('token', 'token');

$checkout->step('Add to cart')
    ->post("$base/api/v1/cart/items", '{"product_id":${product_id},"quantity":${quantity}}')
    ->header('Content-Type', 'application/json')
    ->header('Authorization', 'Bearer ${token}')
    ->validateStatus('cart item created', 201);

$checkout->step('Checkout')
    ->post("$base/api/v1/checkout", '{}')
    ->header('Content-Type', 'application/json')
    ->header('Authorization', 'Bearer ${token}')
    ->validateStatus('order created', 201)
    ->extractFromJson('order_id', 'data.order_id');
}

// ---------------------------------------------------------------------------
// Scenario 3: HTML shopper (session cookie + CSRF, the way a browser does it)
// ---------------------------------------------------------------------------
if ($wants('html')) {
$html = $test->scenario('HTML: login, add to cart, checkout')
    ->setWeight(30)
    ->setThinkTime('2s')
    ->autoHandleCookies()
    ->setDataSourceConfiguration($users(3));

$html->step('Login page')
    ->get("$base/login")
    ->header('Accept', 'text/html')
    ->validateStatus('login page ok', 200)
    ->extractFromHtml('login_csrf', 'input[name="_csrf_token"]', 'value');

$html->step('Submit login form')
    ->post("$base/login", '_username=${email}&_password=${password}&_csrf_token=${login_csrf}')
    ->header('Content-Type', 'application/x-www-form-urlencoded')
    // Symfony answers 302 on both success (-> /) and failure (-> /login);
    // the next step proves the session is real.
    ->validateStatus('login redirect', 302);

$html->step('Cart page (proves session)')
    ->get("$base/cart")
    ->header('Accept', 'text/html')
    ->validateStatus('logged-in cart ok', 200);

$html->step('Product page')
    ->get("$base/products/\${product_id}")
    ->header('Accept', 'text/html')
    ->validateStatus('product page ok', 200)
    ->extractFromHtml('form_csrf', 'input[name="add_to_cart[_token]"]', 'value');

$html->step('Add to cart form')
    ->post("$base/cart/add", 'add_to_cart[product_id]=${product_id}&add_to_cart[quantity]=${quantity}&add_to_cart[_token]=${form_csrf}')
    ->header('Content-Type', 'application/x-www-form-urlencoded')
    ->validateStatus('added, redirect to cart', 302);

$html->step('Cart page')
    ->get("$base/cart")
    ->header('Accept', 'text/html')
    ->validateStatus('cart ok', 200)
    ->extractFromHtml('checkout_csrf', 'form.checkout-form input[name="_token"]', 'value')
    ->extractFromHtml('logout_csrf', 'form[action="/logout"] input[name="_csrf_token"]', 'value');

$html->step('Checkout form')
    ->post("$base/checkout", '_token=${checkout_csrf}')
    ->header('Content-Type', 'application/x-www-form-urlencoded')
    ->validateStatus('order placed, redirect', 302);

// A VU keeps its cookie jar for the whole run, so end the session the way a
// browser would; otherwise the next iteration's GET /login answers 302.
$html->step('Logout')
    ->post("$base/logout", '_csrf_token=${logout_csrf}')
    ->header('Content-Type', 'application/x-www-form-urlencoded')
    ->validateStatus('logged out, redirect', 302);
}

// ---------------------------------------------------------------------------
// Scenario 4: API flash sale (hot row + oversell guard)
// ---------------------------------------------------------------------------
// Every row in users-flash-sale.csv points at the same product, which the
// fixtures seed with only 500 units. Most checkouts must therefore answer
// 409 once it sells out, and that is correct behaviour, so the checkout step
// has no status validator: the SDK can only assert one expected code per
// step. The real assertion is `bin/console app:flash-sale report` after the
// run (stock exactly 0, never negative, units sold == initial stock). The
// 409s still show up in the engine's error breakdown as HTTP 4xx.
// Reset between runs with `bin/console app:flash-sale reset`.
if ($wants('flash-sale')) {
$flash = $test->scenario('API: flash sale (oversell guard)')
    ->setWeight(15)
    ->setThinkTime('1s')
    ->setDataSourceConfiguration($users('flash-sale'));

$flash->step('Login (JWT)')
    ->post("$base/api/v1/login", '{"email":"${email}","password":"${password}"}')
    ->header('Content-Type', 'application/json')
    ->validateStatus('login ok', 200)
    ->extractFromJson('token', 'token');

$flash->step('Add flash-sale item')
    ->post("$base/api/v1/cart/items", '{"product_id":${product_id},"quantity":${quantity}}')
    ->header('Content-Type', 'application/json')
    ->header('Authorization', 'Bearer ${token}')
    ->validateStatus('cart item created', 201);

$flash->step('Checkout (201 until sold out, then 409)')
    ->post("$base/api/v1/checkout", '{}')
    ->header('Content-Type', 'application/json')
    ->header('Authorization', 'Bearer ${token}');
}

// ---------------------------------------------------------------------------
// Run (only when executed directly; `require` returns the configured test so
// PHPUnit or another script can set its own load and thresholds)
// ---------------------------------------------------------------------------
if (!isset($argv[0]) || realpath($argv[0]) !== __FILE__) {
    return $test;
}

if ($apiKey = getenv('VOLTTEST_API_KEY')) {
    $test->cloud($apiKey);
    if ($regions = getenv('REGIONS')) {
        // e.g. REGIONS="us-east-1:100" (percent per region)
        $parsed = [];
        foreach (explode(',', $regions) as $pair) {
            [$region, $pct] = explode(':', $pair);
            $parsed[$region] = (int) $pct;
        }
        $test->regions($parsed);
    }

    $run = $test->run(true);
    echo "Cloud run {$run->getRunId()} status {$run->getStatus()}\n";
    echo "Dashboard: {$run->getDashboardUrl()}\n";
    exit($run->isSuccessful() ? 0 : 1);
}

$result = $test->run(true);

echo "\n=== Summary ===\n";
echo 'Requests:      '.$result->getTotalRequests()."\n";
echo 'Success rate:  '.$result->getSuccessRate()."%\n";
echo 'RPS:           '.$result->getRequestsPerSecond()."\n";
echo 'Avg / p95 / p99: '.$result->getAvgResponseTime().' / '.$result->getP95ResponseTime().' / '.$result->getP99ResponseTime()."\n";
